# Generated by Django 6.1.1 on 2026-09-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_department_delete_role_alter_userinfo_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='caption',
            new_name='title',
        ),
    ]
